name: Build Windows
on:
  push:
    branches: [ windows ]
    # paths:
    #   - 'src/**'
    #   - 'scripts/**'
    #   - 'meson.build'

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            git
            axel
            meson
            zip
            unzip
            mingw-w64-x86_64-vala
            mingw-w64-x86_64-aria2
            mingw-w64-x86_64-libsoup
      - name: Setup Node
        run: | 
          wget https://nodejs.org/dist/v19.5.0/node-v19.5.0-win-x64.zip -O node.zip
          unzip node.zip
          cp -R node-*/* /usr/bin
      - name: Build
        run: | 
          meson builddir
          ninja -C builddir
          ninja -C builddir release-windows