name: Build
on:
  push:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Install dependencies
        run: | 
          pip install meson ninja
          sudo apt-add-repository --yes ppa:vala-team
          sudo apt-get update
          sudo apt-get -y install valac libglib2.0-dev libsoup2.4-dev libgee-0.8-dev axel aria2 libfuse2
      - name: Build
        run: | 
          meson builddir
          ninja -C builddir
          ninja -C builddir release